// Code generated by MockGen. DO NOT EDIT.
// Source: task.go

// Package mock_main is a generated GoMock package.
package mock_main

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockNtpClient is a mock of iNtpClient interface.
type MockNtpClient struct {
	ctrl     *gomock.Controller
	recorder *MockNtpClientMockRecorder
}

// MockNtpClientMockRecorder is the mock recorder for MockNtpClient.
type MockNtpClientMockRecorder struct {
	mock *MockNtpClient
}

// NewMockNtpClient creates a new mock instance.
func NewMockNtpClient(ctrl *gomock.Controller) *MockNtpClient {
	mock := &MockNtpClient{ctrl: ctrl}
	mock.recorder = &MockNtpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNtpClient) EXPECT() *MockNtpClientMockRecorder {
	return m.recorder
}

// Time mocks base method.
func (m *MockNtpClient) Time() (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Time")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Time indicates an expected call of Time.
func (mr *MockNtpClientMockRecorder) Time() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Time", reflect.TypeOf((*MockNtpClient)(nil).Time))
}
